#!/bin/bash

set -e

cd `dirname $0`
echo 'kali'>/etc/hostname
echo -e 'nameserver 8.8.8.8\nnameserver 8.8.4.4'>/etc/resolv.conf
echo 'deb http://kali.download/kali kali-rolling main non-free contrib' > /etc/apt/sources.list
apt update
apt upgrade -y
apt install -y kali-linux-core kali-defaults phosh-phone pinephone-tweaks u-boot-menu rsync wget curl vim gnome-text-editor megapixels systemd-timesyncd inetutils-ping libcanberra-pulse firmware-realtek-rtl8723cs-bt
ln -rs /usr/share/alsa/ucm2/PinePhone/PinePhone.conf /usr/share/alsa/ucm2/conf.d/simple-card/

adduser --disabled-password --gecos "" kali
usermod --password `echo 8888 | openssl passwd -1 -stdin` kali
usermod -aG dialout,sudo,audio,video,plugdev,input,render,bluetooth,feedbackd kali
systemctl enable phosh
sed -i 's/-0.07/0/;s/-0.13/0/' /usr/share/plymouth/themes/kali/kali.script
sed -i 's/bash/zsh/' /etc/passwd

rsync -HPavz confs/ /

for i in `ls debs`
do
	apt install -y ./debs/$i
done

chown kali:kali -R /home/kali

plymouth-set-default-theme -R kali

for i in $(cat svcs)
do
	systemctl enable $i
done
echo > /etc/resolv.conf
apt clean
sed -i "/picture-uri/cpicture-uri='file:\/\/\/usr\/share\/backgrounds\/kali\/kali-layers.xml'" /usr/share/glib-2.0/schemas/11_mobile.gschema.override
glib-compile-schemas /usr/share/glib-2.0/schemas

